// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/system/detection.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerDetectionSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*DetectedPlayer      `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDetectionSnapshot) Reset() {
	*x = PlayerDetectionSnapshot{}
	mi := &file_modules_game_core_system_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDetectionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDetectionSnapshot) ProtoMessage() {}

func (x *PlayerDetectionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDetectionSnapshot.ProtoReflect.Descriptor instead.
func (*PlayerDetectionSnapshot) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_detection_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerDetectionSnapshot) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *PlayerDetectionSnapshot) GetPlayers() []*DetectedPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

type DetectedPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Position      *Vector2               `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Facing        *Vector2               `protobuf:"bytes,5,opt,name=facing,proto3" json:"facing,omitempty"`
	Direction     *Vector2               `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	Characters    []*CharacterSnapshot   `protobuf:"bytes,7,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectedPlayer) Reset() {
	*x = DetectedPlayer{}
	mi := &file_modules_game_core_system_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedPlayer) ProtoMessage() {}

func (x *DetectedPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectedPlayer.ProtoReflect.Descriptor instead.
func (*DetectedPlayer) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_detection_proto_rawDescGZIP(), []int{1}
}

func (x *DetectedPlayer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DetectedPlayer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DetectedPlayer) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DetectedPlayer) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *DetectedPlayer) GetFacing() *Vector2 {
	if x != nil {
		return x.Facing
	}
	return nil
}

func (x *DetectedPlayer) GetDirection() *Vector2 {
	if x != nil {
		return x.Direction
	}
	return nil
}

func (x *DetectedPlayer) GetCharacters() []*CharacterSnapshot {
	if x != nil {
		return x.Characters
	}
	return nil
}

type Vector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	mi := &file_modules_game_core_system_detection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_detection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_detection_proto_rawDescGZIP(), []int{2}
}

func (x *Vector2) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type CharacterSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        float64                `protobuf:"fixed64,1,opt,name=health,proto3" json:"health,omitempty"`
	Damage        float64                `protobuf:"fixed64,2,opt,name=damage,proto3" json:"damage,omitempty"`
	MoveSpeed     float64                `protobuf:"fixed64,3,opt,name=move_speed,json=moveSpeed,proto3" json:"move_speed,omitempty"`
	AttackSpeed   float64                `protobuf:"fixed64,4,opt,name=attack_speed,json=attackSpeed,proto3" json:"attack_speed,omitempty"`
	AttackRange   float64                `protobuf:"fixed64,5,opt,name=attack_range,json=attackRange,proto3" json:"attack_range,omitempty"`
	RegenRate     float64                `protobuf:"fixed64,6,opt,name=regen_rate,json=regenRate,proto3" json:"regen_rate,omitempty"`
	DamageRatio   float64                `protobuf:"fixed64,7,opt,name=damage_ratio,json=damageRatio,proto3" json:"damage_ratio,omitempty"`
	WeaponType    string                 `protobuf:"bytes,8,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterSnapshot) Reset() {
	*x = CharacterSnapshot{}
	mi := &file_modules_game_core_system_detection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSnapshot) ProtoMessage() {}

func (x *CharacterSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_detection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSnapshot.ProtoReflect.Descriptor instead.
func (*CharacterSnapshot) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_detection_proto_rawDescGZIP(), []int{3}
}

func (x *CharacterSnapshot) GetHealth() float64 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *CharacterSnapshot) GetDamage() float64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *CharacterSnapshot) GetMoveSpeed() float64 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *CharacterSnapshot) GetAttackSpeed() float64 {
	if x != nil {
		return x.AttackSpeed
	}
	return 0
}

func (x *CharacterSnapshot) GetAttackRange() float64 {
	if x != nil {
		return x.AttackRange
	}
	return 0
}

func (x *CharacterSnapshot) GetRegenRate() float64 {
	if x != nil {
		return x.RegenRate
	}
	return 0
}

func (x *CharacterSnapshot) GetDamageRatio() float64 {
	if x != nil {
		return x.DamageRatio
	}
	return 0
}

func (x *CharacterSnapshot) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

var File_modules_game_core_system_detection_proto protoreflect.FileDescriptor

const file_modules_game_core_system_detection_proto_rawDesc = "" +
	"\n" +
	"(modules/game/core/system/detection.proto\x12\x10game.core.system\"i\n" +
	"\x17PlayerDetectionSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12:\n" +
	"\aplayers\x18\x02 \x03(\v2 .game.core.system.DetectedPlayerR\aplayers\"\xd3\x02\n" +
	"\x0eDetectedPlayer\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x125\n" +
	"\bposition\x18\x04 \x01(\v2\x19.game.core.system.Vector2R\bposition\x121\n" +
	"\x06facing\x18\x05 \x01(\v2\x19.game.core.system.Vector2R\x06facing\x127\n" +
	"\tdirection\x18\x06 \x01(\v2\x19.game.core.system.Vector2R\tdirection\x12C\n" +
	"\n" +
	"characters\x18\a \x03(\v2#.game.core.system.CharacterSnapshotR\n" +
	"characters\"%\n" +
	"\aVector2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\x8b\x02\n" +
	"\x11CharacterSnapshot\x12\x16\n" +
	"\x06health\x18\x01 \x01(\x01R\x06health\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\x01R\x06damage\x12\x1d\n" +
	"\n" +
	"move_speed\x18\x03 \x01(\x01R\tmoveSpeed\x12!\n" +
	"\fattack_speed\x18\x04 \x01(\x01R\vattackSpeed\x12!\n" +
	"\fattack_range\x18\x05 \x01(\x01R\vattackRange\x12\x1d\n" +
	"\n" +
	"regen_rate\x18\x06 \x01(\x01R\tregenRate\x12!\n" +
	"\fdamage_ratio\x18\a \x01(\x01R\vdamageRatio\x12\x1f\n" +
	"\vweapon_type\x18\b \x01(\tR\n" +
	"weaponTypeB3Z1squad-survival-be/modules/game/core/system;systemb\x06proto3"

var (
	file_modules_game_core_system_detection_proto_rawDescOnce sync.Once
	file_modules_game_core_system_detection_proto_rawDescData []byte
)

func file_modules_game_core_system_detection_proto_rawDescGZIP() []byte {
	file_modules_game_core_system_detection_proto_rawDescOnce.Do(func() {
		file_modules_game_core_system_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_system_detection_proto_rawDesc), len(file_modules_game_core_system_detection_proto_rawDesc)))
	})
	return file_modules_game_core_system_detection_proto_rawDescData
}

var file_modules_game_core_system_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_modules_game_core_system_detection_proto_goTypes = []any{
	(*PlayerDetectionSnapshot)(nil), // 0: game.core.system.PlayerDetectionSnapshot
	(*DetectedPlayer)(nil),          // 1: game.core.system.DetectedPlayer
	(*Vector2)(nil),                 // 2: game.core.system.Vector2
	(*CharacterSnapshot)(nil),       // 3: game.core.system.CharacterSnapshot
}
var file_modules_game_core_system_detection_proto_depIdxs = []int32{
	1, // 0: game.core.system.PlayerDetectionSnapshot.players:type_name -> game.core.system.DetectedPlayer
	2, // 1: game.core.system.DetectedPlayer.position:type_name -> game.core.system.Vector2
	2, // 2: game.core.system.DetectedPlayer.facing:type_name -> game.core.system.Vector2
	2, // 3: game.core.system.DetectedPlayer.direction:type_name -> game.core.system.Vector2
	3, // 4: game.core.system.DetectedPlayer.characters:type_name -> game.core.system.CharacterSnapshot
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_modules_game_core_system_detection_proto_init() }
func file_modules_game_core_system_detection_proto_init() {
	if File_modules_game_core_system_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_system_detection_proto_rawDesc), len(file_modules_game_core_system_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_system_detection_proto_goTypes,
		DependencyIndexes: file_modules_game_core_system_detection_proto_depIdxs,
		MessageInfos:      file_modules_game_core_system_detection_proto_msgTypes,
	}.Build()
	File_modules_game_core_system_detection_proto = out.File
	file_modules_game_core_system_detection_proto_goTypes = nil
	file_modules_game_core_system_detection_proto_depIdxs = nil
}
