// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: modules/game/core/system/state.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	PlayerCount   int32                  `protobuf:"varint,2,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_modules_game_core_system_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_modules_game_core_system_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_modules_game_core_system_state_proto_rawDescGZIP(), []int{0}
}

func (x *StateSnapshot) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *StateSnapshot) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

var File_modules_game_core_system_state_proto protoreflect.FileDescriptor

const file_modules_game_core_system_state_proto_rawDesc = "" +
	"\n" +
	"$modules/game/core/system/state.proto\x12\x10game.core.system\"F\n" +
	"\rStateSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12!\n" +
	"\fplayer_count\x18\x02 \x01(\x05R\vplayerCountB3Z1squad-survival-be/modules/game/core/system;systemb\x06proto3"

var (
	file_modules_game_core_system_state_proto_rawDescOnce sync.Once
	file_modules_game_core_system_state_proto_rawDescData []byte
)

func file_modules_game_core_system_state_proto_rawDescGZIP() []byte {
	file_modules_game_core_system_state_proto_rawDescOnce.Do(func() {
		file_modules_game_core_system_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_game_core_system_state_proto_rawDesc), len(file_modules_game_core_system_state_proto_rawDesc)))
	})
	return file_modules_game_core_system_state_proto_rawDescData
}

var file_modules_game_core_system_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_modules_game_core_system_state_proto_goTypes = []any{
	(*StateSnapshot)(nil), // 0: game.core.system.StateSnapshot
}
var file_modules_game_core_system_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_game_core_system_state_proto_init() }
func file_modules_game_core_system_state_proto_init() {
	if File_modules_game_core_system_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_game_core_system_state_proto_rawDesc), len(file_modules_game_core_system_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_game_core_system_state_proto_goTypes,
		DependencyIndexes: file_modules_game_core_system_state_proto_depIdxs,
		MessageInfos:      file_modules_game_core_system_state_proto_msgTypes,
	}.Build()
	File_modules_game_core_system_state_proto = out.File
	file_modules_game_core_system_state_proto_goTypes = nil
	file_modules_game_core_system_state_proto_depIdxs = nil
}
